project_id = "apbfdrwneoohudetgcve"

[functions.process-order]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.manage-products]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false
